In [1]:
# Librerías
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re

In [11]:
nomenclatura = pd.read_csv('nomenclaturas/nomenclatura_ecobici.csv', encoding='latin1')
nomenclatura.head()

sistema num_cicloe                 calle_prin          calle_secu  \
0  Ecobici        100            20 de Noviembre             Mesones   
1  Ecobici        102                  Echeveste       Simon Bolivar   
2  Ecobici        103  Joaquin Velazquez de Leon  Garcia Icazbalceta   
3  Ecobici        104               San Jeronimo  Isabel la Catolica   
4  Ecobici        105               San Jeronimo        5 de Febrero   

      colonia    alcaldia    latitud   longitud sitio_de_e    estatus  
0      Centro  Cuauhtemoc  19.428485 -99.133800   Banqueta  Instalada  
1      Centro  Cuauhtemoc  19.428214 -99.139494   Banqueta  Instalada  
2  San Rafael  Cuauhtemoc  19.441533 -99.165268     Arroyo  Instalada  
3      Centro  Cuauhtemoc  19.427059 -99.137116   Banqueta  Instalada  
4      Centro  Cuauhtemoc  19.426755 -99.135014     Arroyo  Instalada

In [12]:
# Verificar si hay valores en 'num_cicloestacion' que no son enteros
non_integer_values = nomenclatura[~nomenclatura['num_cicloe'].apply(lambda x: isinstance(x, int))]
print(non_integer_values)

     sistema num_cicloe                 calle_prin              calle_secu  \
0    Ecobici        100            20 de Noviembre                 Mesones   
1    Ecobici        102                  Echeveste           Simon Bolivar   
2    Ecobici        103  Joaquin Velazquez de Leon      Garcia Icazbalceta   
3    Ecobici        104               San Jeronimo      Isabel la Catolica   
4    Ecobici        105               San Jeronimo            5 de Febrero   
..       ...        ...                        ...                     ...   
672  Ecobici    268-269       Luis Donaldo Colosio            Jesus Garcia   
673  Ecobici    271-272               Jesus Garcia       Carlos J. Meneses   
674  Ecobici    273-274       Luis Donaldo Colosio            Jesus Garcia   
675  Ecobici    390-391                        Oso            Felix Cuevas   
676  Ecobici    445-446                       Riff  Avenida Rio Churubusco   

                       colonia       alcaldia    latitud   long

In [13]:
# Cambiar el nombre de la columna 'num_cicloestacion' a 'id'
nomenclatura.rename(columns={'num_cicloe': 'id'}, inplace=True)

# Guardar los cambios en el archivo CSV
nomenclatura.to_csv('nomenclaturas/estaciones_ecobici.csv', index=False)

In [14]:
nomenclatura.head()

sistema   id                 calle_prin          calle_secu     colonia  \
0  Ecobici  100            20 de Noviembre             Mesones      Centro   
1  Ecobici  102                  Echeveste       Simon Bolivar      Centro   
2  Ecobici  103  Joaquin Velazquez de Leon  Garcia Icazbalceta  San Rafael   
3  Ecobici  104               San Jeronimo  Isabel la Catolica      Centro   
4  Ecobici  105               San Jeronimo        5 de Febrero      Centro   

     alcaldia    latitud   longitud sitio_de_e    estatus  
0  Cuauhtemoc  19.428485 -99.133800   Banqueta  Instalada  
1  Cuauhtemoc  19.428214 -99.139494   Banqueta  Instalada  
2  Cuauhtemoc  19.441533 -99.165268     Arroyo  Instalada  
3  Cuauhtemoc  19.427059 -99.137116   Banqueta  Instalada  
4  Cuauhtemoc  19.426755 -99.135014     Arroyo  Instalada

In [15]:
#total de estaciones
nomenclatura.shape[0]

677

In [16]:
nomenclatura['id'].unique()

array(['100', '102', '103', '104', '105', '106', '109', '110', '111',
       '112', '113', '114', '115', '116', '117', '118', '119', '120',
       '121', '122', '123', '124', '125', '126', '127', '128', '129',
       '130', '131', '132', '133', '134', '135', '136', '137', '138',
       '139', '140', '141', '142', '143', '144', '145', '146', '147',
       '148', '149', '150', '151', '152', '153', '154', '155', '156',
       '157', '160', '161', '162', '163', '164', '165', '166', '167',
       '168', '169', '170', '171', '172', '173', '174', '175', '176',
       '177', '178', '179', '180', '181', '182', '183', '184', '185',
       '186', '187', '188', '189', '190', '191', '194', '195', '196',
       '197', '198', '199', '200', '201', '202', '203', '204', '205',
       '206', '207', '208', '209', '210', '211', '212', '213', '214',
       '215', '216', '217', '218', '219', '220', '221', '222', '223',
       '224', '225', '226', '227', '228', '229', '230', '231', '232',
       '233', '234',

In [17]:
estaciones_seguidas = nomenclatura[nomenclatura['id'].str.contains('-', na=False)]
print(estaciones_seguidas['id'].unique())

['107-108' '158-159' '192-193' '235-236' '237-238' '264-275' '266-267'
 '268-269' '271-272' '273-274' '390-391' '445-446']


In [19]:
def procesar_estacion(valor):
    # Si el valor es un número entero, lo dejamos igual
    try:
        return int(valor)
    except ValueError:
        pass

    # Si el valor tiene el formato "%d-%d", obtenemos el primer número
    if re.match(r'^\d+-\d+$', valor):
        return int(valor.split('-')[0])

    # Si no está en el diccionario, pedimos manualmente la estación
    print(f"Valor inesperado: {valor}")
    nuevo_valor = input("Ingresa manualmente la estación correcta: ")
    
    return int(nuevo_valor)

In [20]:
nomenclatura['id'] = nomenclatura['id'].apply(procesar_estacion)

In [21]:
nomenclatura.to_csv('nomenclaturas/estaciones_ecobici.csv', index=False)

In [26]:
nomenclatura['id'].unique()

array([100, 102, 103, 104, 105, 106, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 194, 195, 196, 197,
       198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210,
       211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
       224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 239, 240,
       241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253,
       254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 265, 270, 276,
       277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 30

Para ver lo de las estaciones faltantes

In [4]:
def leer_matriz(nombre_archivo):
    matriz = []
    with open(nombre_archivo, 'r') as archivo:
        archivo.readline()
        archivo.readline()
        for linea in archivo:
            fila = [float(valor) for valor in linea.strip().split()]
            matriz.append(fila)
    return np.array(matriz)

In [2]:
n_nueva = pd.read_csv('nomenclaturas/estaciones_ecobici.csv')
n_nueva.head()

sistema   id                 calle_prin          calle_secu     colonia  \
0  Ecobici  100            20 de Noviembre             Mesones      Centro   
1  Ecobici  102                  Echeveste       Simon Bolivar      Centro   
2  Ecobici  103  Joaquin Velazquez de Leon  Garcia Icazbalceta  San Rafael   
3  Ecobici  104               San Jeronimo  Isabel la Catolica      Centro   
4  Ecobici  105               San Jeronimo        5 de Febrero      Centro   

     alcaldia    latitud   longitud sitio_de_e    estatus  
0  Cuauhtemoc  19.428485 -99.133800   Banqueta  Instalada  
1  Cuauhtemoc  19.428214 -99.139494   Banqueta  Instalada  
2  Cuauhtemoc  19.441533 -99.165268     Arroyo  Instalada  
3  Cuauhtemoc  19.427059 -99.137116   Banqueta  Instalada  
4  Cuauhtemoc  19.426755 -99.135014     Arroyo  Instalada

In [3]:
n_vieja = pd.read_csv('nomenclaturas/estaciones_ecobici_viejo.csv')
n_vieja.head()

sistema  num_cicloestacion                        nombre   calle_principal  \
0  ECOBICI                  1         Río Sena - Río Balsas          Río Sena   
1  ECOBICI                  2  Río Guadalquivir - Río Nazas  Río Guadalquivir   
2  ECOBICI                  3         Reforma - Insurgentes           Reforma   
3  ECOBICI                  4         Río Nilo - Río Pánuco          Río Nilo   
4  ECOBICI                  5        Río Pánuco - Río Tíber        Río Pánuco   

  calle_secundaria     colonia    alcaldia    latitud   longitud tipo_ce  \
0       Río Balsas  Cuauhtémoc  CUAUHTEMOC  19.433590 -99.167819      4G   
1        Río Nazas  Cuauhtémoc  CUAUHTEMOC  19.430510 -99.171201      3G   
2      Insurgentes  Tabacalera  CUAUHTEMOC  19.431630 -99.158547      4G   
3       Río Pánuco  Cuauhtémoc  CUAUHTEMOC  19.428491 -99.171693      3G   
4        Río Tíber  Cuauhtémoc  CUAUHTEMOC  19.429804 -99.169451      3G   

   candados  
0        27  
1        21  
2        36  
3        15  
4        12

In [6]:
print(np.sort(n_nueva['id'].unique()))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 102 103 104 105 106 107 109 110
 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128
 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 149 150 151 152 153 154 155 156 157 158 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 194 195 196 197 198 199 200 201 202
 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220
 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 237 239 240
 241 242 243 244 245 246 247 248 249 250 251 252 25

In [18]:
est_nueva = np.sort(n_nueva['id'].unique())
print(est_nueva)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 102 103 104 105 106 107 109 110
 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128
 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 149 150 151 152 153 154 155 156 157 158 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 194 195 196 197 198 199 200 201 202
 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220
 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 237 239 240
 241 242 243 244 245 246 247 248 249 250 251 252 25

In [7]:
print(np.sort(n_vieja['num_cicloestacion'].unique()))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [19]:
est_vieja = np.sort(n_vieja['num_cicloestacion'].unique())
print(est_vieja)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [10]:
est_2019 = leer_matriz('Adj_eco/matrices_estaciones/estaciones_2019.txt')
est_2019 = est_2019[:,0].astype(int)
est_2019

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [11]:
est_2020 = leer_matriz('Adj_eco/matrices_estaciones/estaciones_2020.txt')
est_2020 = est_2020[:,0].astype(int)
est_2020

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   56,
         57,   58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
         68,   69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
         79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
         90,   91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
        102,  103,  104,  105,  106,  107,  108,  109,  110,  111,  112,
        113,  114,  115,  116,  117,  118,  119,  120,  121,  122,  123,
        124,  125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
        135,  136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
        146,  147,  148,  149,  150,  151,  152,  1

In [12]:
est_2021 = leer_matriz('Adj_eco/matrices_estaciones/estaciones_2021.txt')
est_2021 = est_2021[:,0].astype(int)
est_2021

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 18

In [13]:
est_2022 = leer_matriz('Adj_eco/matrices_estaciones/estaciones_2022.txt')
est_2022 = est_2022[:,0].astype(int)
est_2022

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  102,  103,  104,  105,  106,  107,  108,  109,  110,  111,
        112,  113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
        123,  124,  125,  126,  127,  128,  129,  130,  131,  132,  133,
        134,  135,  136,  137,  138,  139,  140,  141,  142,  143,  144,
        145,  146,  147,  148,  149,  150,  151,  1

In [14]:
est_2023 = leer_matriz('Adj_eco/matrices_estaciones/estaciones_2023.txt')
est_2023 = est_2023[:,0].astype(int)
est_2023

array([      1,       2,       3,       4,       5,       6,       7,
             8,       9,      10,      11,      12,      13,      14,
            15,      16,      17,      18,      19,      20,      21,
            22,      23,      24,      25,      26,      27,      28,
            29,      30,      31,      32,      33,      34,      35,
            36,      37,      38,      39,      40,      41,      42,
            43,      44,      45,      46,      47,      48,      49,
            50,      51,      52,      53,      54,      55,      56,
            57,      58,      59,      60,      61,      62,      63,
            64,      65,      66,      67,      68,      69,      70,
            71,      72,      73,      74,      75,      76,      77,
            78,      79,      80,      81,      82,      83,      84,
            85,      86,      87,      88,      89,      90,      91,
            92,      93,      94,      95,      96,      97,      98,
            99,     

In [15]:
est_2024 = leer_matriz('Adj_eco/matrices_estaciones/estaciones_2024.txt')
est_2024 = est_2024[:,0].astype(int)
est_2024

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  102,  103,  104,  105,  106,  107,  109,  110,  111,  112,
        113,  114,  115,  116,  117,  118,  119,  120,  121,  122,  123,
        124,  125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
        135,  136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
        146,  147,  148,  149,  150,  151,  152,  1

In [20]:
# estaciones viejas que no están en las nuevas
estaciones_viejas_no_nuevas = np.setdiff1d(est_vieja, est_nueva)
print(estaciones_viejas_no_nuevas)

[101 108 159 193 236 238 267 269 272 274 275 289 311 344 350 364 368 376
 379 382 383 388 391 400 403 406 408 410 411 418 426 431 435 446]


In [22]:
# Crear una lista para almacenar los nuevos datos
nuevos_datos = []

for estacion in estaciones_viejas_no_nuevas:
    current_station = n_vieja[n_vieja['num_cicloestacion'] == estacion]
    
    # Verificar que current_station no esté vacío
    if not current_station.empty:
        nuevos_datos.append({
            'sistema': 'ECOBICI',
            'id': estacion,
            'calle_prin': current_station['calle_principal'].values[0],
            'calle_secu': current_station['calle_secundaria'].values[0],
            'colonia': current_station['colonia'].values[0],
            'alcaldia': current_station['alcaldia'].values[0],
            'latitud': current_station['latitud'].values[0],
            'longitud': current_station['longitud'].values[0],
            'sitio_de_e': 'antigua',
            'estatus': 'antigua'
        })

# Crear un DataFrame con los nuevos datos y concatenarlo con n_nueva
n_nueva = pd.concat([n_nueva, pd.DataFrame(nuevos_datos)], ignore_index=True)


In [23]:
n_nueva.to_csv('nomenclaturas/estaciones_ecobici.csv', index=False)

In [25]:
est_nueva = np.sort(n_nueva['id'].unique())
estaciones_viejas_no_nuevas2 = np.setdiff1d(est_vieja, est_nueva)
print(estaciones_viejas_no_nuevas2)

[]


In [27]:
# estaciones faltantes en 2019
missing_2019 = np.setdiff1d(est_2019, est_nueva)
print(missing_2019)

[1000 1001 1002 3000 3001 3002]


In [28]:
missing_2020 = np.setdiff1d(est_2020, est_nueva)
print(missing_2020)

[3000 3001 3002]


In [29]:
missing_2021 = np.setdiff1d(est_2021, est_nueva)
print(missing_2021)

[]


In [30]:
missing_2022 = np.setdiff1d(est_2022, est_nueva)
print(missing_2022)

[1000 1002]


In [37]:
missing_2023 = np.setdiff1d(est_2023, est_nueva)
print(missing_2023)

[   1000 4422222]


In [38]:
missing_2024 = np.setdiff1d(est_2024, est_nueva)
print(missing_2024)

[1000 1002]


In [39]:
estaciones_faltantes = np.unique(np.concatenate([missing_2019, missing_2020, missing_2021, missing_2022, missing_2023, missing_2024]))
print(estaciones_faltantes)

[   1000    1001    1002    3000    3001    3002 4422222]


Hay que tomar una descisión sobre esas estaciones...

In [41]:
data_2019 = pd.read_csv('ecobici/2019.csv', encoding='latin1', low_memory=False)
data_2019.head()

Genero_Usuario  Edad_Usuario   Bici  Ciclo_Estacion_Retiro Fecha_Retiro  \
0              M            36  11444                     67   01/01/2019   
1              M            36   9196                     55   01/01/2019   
2              M            38   2612                     29   01/01/2019   
3              M            43   7463                     29   01/01/2019   
4              M            37   3987                    136   01/01/2019   

  Hora_Retiro  Ciclo_Estacion_Arribo Fecha_Arribo Hora_Arribo  Tiempo_viaje  
0     0:08:44                     36   01/01/2019     0:14:03      5.316667  
1     0:12:05                    136   01/01/2019     0:42:11     30.100000  
2     0:13:15                    115   01/01/2019     0:37:47     24.533333  
3     0:13:36                    115   01/01/2019     0:38:04     24.466667  
4     0:15:30                     35   01/01/2019     0:22:47      7.283333

In [43]:
np.sum(data_2019['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2019['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

173

In [44]:
data_2019.drop(data_2019[data_2019['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2019['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes)].index, inplace=True)

In [45]:
np.sum(data_2019['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2019['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

0

In [46]:
data_2019.to_csv('ecobici/2019.csv', index=False)
del data_2019

In [47]:
data_2020 = pd.read_csv('ecobici/2020.csv', encoding='latin1', low_memory=False)
data_2020.head()

Genero_Usuario  Edad_Usuario   Bici  Ciclo_Estacion_Retiro Fecha_Retiro  \
0              F          33.0   8744                   52.0   01/01/2020   
1              M          30.0   7865                   31.0   01/01/2020   
2              F          36.0   7819                  251.0   01/01/2020   
3              F          33.0  11258                    3.0   01/01/2020   
4              M          29.0   7722                  136.0   01/01/2020   

  Hora_Retiro  Ciclo_Estacion_Arribo Fecha_Arribo Hora_Arribo  BikeID  \
0     0:05:06                      3   01/01/2020     0:13:00     NaN   
1     0:09:50                    271   01/01/2020     0:21:30     NaN   
2     0:13:25                    150   01/01/2020     0:26:10     NaN   
3     0:15:22                      1   01/01/2020     0:25:29     NaN   
4     0:18:42                     63   01/01/2020     0:24:01     NaN   

   Tiempo_viaje  
0      7.900000  
1     11.666667  
2     12.750000  
3     10.116667  
4      5.316667

In [48]:
np.sum(data_2020['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2020['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

35

In [49]:
data_2020.drop(data_2020[data_2020['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2020['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes)].index, inplace=True)

In [50]:
np.sum(data_2020['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2020['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

0

In [51]:
data_2020.to_csv('ecobici/2020.csv', index=False)
del data_2020

In [52]:
data_2021 = pd.read_csv('ecobici/2021.csv', encoding='latin1', low_memory=False)
data_2021.head()

Genero_Usuario  Edad_Usuario     Bici  Ciclo_Estacion_Retiro Fecha_Retiro  \
0              M          32.0   7608.0                     18   01/01/2021   
1              M          24.0   8324.0                     76   01/01/2021   
2              F          35.0   6787.0                    281   01/01/2021   
3              F          34.0  11875.0                    405   01/01/2021   
4              M          26.0   8164.0                     30   01/01/2021   

  Hora_Retiro  Ciclo_Estacion_Arribo Fecha_Arribo Hora_Arribo  Tiempo_viaje  
0    07:05:04                    143   01/01/2021    07:13:25      8.350000  
1    09:03:35                     76   01/01/2021    09:08:08      4.550000  
2    09:22:41                     61   01/01/2021    09:50:03     27.366667  
3    10:21:21                    431   01/01/2021    10:27:16      5.916667  
4    11:52:38                    126   01/01/2021    12:07:30     14.866667

In [54]:
np.sum(data_2021['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) & data_2021['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

0

In [55]:
del data_2021

In [56]:
data_2022 = pd.read_csv('ecobici/2022.csv', encoding='latin1', low_memory=False)
data_2022.head()

Genero_Usuario  Edad_Usuario     Bici  Ciclo_Estacion_Retiro Fecha_Retiro  \
0              M          40.0   8811.0                    282   04/01/2022   
1              M          40.0   8752.0                    282   06/01/2022   
2              M          40.0  12028.0                    282   11/01/2022   
3              M          40.0   7102.0                    282   12/01/2022   
4              M          40.0   4261.0                    282   13/01/2022   

  Hora_Retiro  Ciclo_Estacion_Arribo Fecha_Arribo Hora_Arribo Genero_usuario  \
0    07:49:31                    295   04/01/2022    07:52:28            NaN   
1    07:45:59                    295   06/01/2022    07:48:55            NaN   
2    07:51:56                    295   11/01/2022    07:54:29            NaN   
3    07:43:56                    295   12/01/2022    07:46:54            NaN   
4    07:43:09                    281   13/01/2022    07:47:27            NaN   

   Edad_usuario  Tiempo_viaje  
0           NaN      2.950000  
1           NaN      2.933333  
2           NaN      2.550000  
3           NaN      2.966667  
4           NaN      4.300000

In [57]:
np.sum(data_2022['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) & data_2022['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

13

In [58]:
data_2022.drop(data_2022[data_2022['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2022['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes)].index, inplace=True)

In [59]:
np.sum(data_2022['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) & data_2022['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

0

In [60]:
data_2022.to_csv('ecobici/2022.csv', index=False)
del data_2022

In [64]:
data_2023 = pd.read_csv('ecobici/2023.csv', encoding='latin1', low_memory=False)
data_2023.head()

Genero_Usuario  Edad_Usuario     Bici  Ciclo_Estacion_Retiro Fecha_Retiro  \
0              M          45.0  3297082                    150   31/12/2022   
1              F          27.0  8922254                    214   31/12/2022   
2              M          34.0  2320075                    214   31/12/2022   
3              M          58.0  2096493                    137   31/12/2022   
4              M          23.0  6294433                    260   31/12/2022   

  Hora_Retiro  Ciclo_Estacion_Arribo Fecha_Arribo Hora_Arribo  \
0    23:58:00                     40   01/01/2023    00:06:24   
1    23:36:34                     25   01/01/2023    00:07:08   
2    23:36:33                     25   01/01/2023    00:07:12   
3    23:57:19                     36   01/01/2023    00:07:48   
4    23:57:42                     43   01/01/2023    00:09:33   

     Fecha_Hora_Retiro  
0  2022-12-31 23:58:00  
1  2022-12-31 23:36:34  
2  2022-12-31 23:36:33  
3  2022-12-31 23:57:19  
4  2022-12-31 23:57:42

In [65]:
np.sum(data_2023['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2023['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

1222

In [66]:
data_2023.drop(data_2023[data_2023['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2023['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes)].index, inplace=True)

In [67]:
np.sum(data_2023['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) & data_2023['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

0

In [68]:
data_2023.to_csv('ecobici/2023.csv', index=False)
del data_2023

In [69]:
data_2024 = pd.read_csv('ecobici/2024.csv', encoding='latin1', low_memory=False)
data_2024.head()

Genero_Usuario  Edad_Usuario     Bici  Ciclo_Estacion_Retiro Fecha_Retiro  \
0              M          48.0  3371879                    113   31/12/2023   
1              F          26.0  7033434                    281   31/12/2023   
2              F          37.0  7169857                     15   31/12/2023   
3              F          30.0  6368211                    555   31/12/2023   
4              M          30.0  5136924                    555   31/12/2023   

  Hora_Retiro  Ciclo_Estacion_Arribo Fecha_Arribo Hora_Arribo  Tiempo_viaje  
0    23:21:52                    659   01/01/2024    00:00:02     38.166667  
1    23:46:02                     47   01/01/2024    00:00:02     14.000000  
2    23:51:57                    217   01/01/2024    00:00:49      8.866667  
3    23:53:10                      8   01/01/2024    00:02:39      9.483333  
4    23:52:53                      8   01/01/2024    00:02:45      9.866667

In [70]:
np.sum(data_2024['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2024['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

17

In [71]:
data_2024.drop(data_2024[data_2024['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) | data_2024['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes)].index, inplace=True)

In [72]:
np.sum(data_2024['Ciclo_Estacion_Retiro'].isin(estaciones_faltantes) & data_2024['Ciclo_Estacion_Arribo'].isin(estaciones_faltantes))

0

In [73]:
data_2024.to_csv('ecobici/2024.csv', index=False)
del data_2024